#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
$bindir/small-step-progression1 1 100000 >$expected

#generating our results
$bindir/sq-seq --out-binary 1 100000 | $bindir/4sq --in-binary --out-binary --type=fwd-progression1 100000 | $bindir/complete-4sq-progression --in-binary --type=step-progression1 -f 5

#0027.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0027.log
retval=$?

#cleanup
rm $expected
exit $retval
