#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
$bindir/small-step-progression1 1 100000 >$expected
echo "2, 7, 6, 9, 5, 1, 4, 3, 8, " >$expected


#generating our results
echo "1, 2, 3, 4, 5, 6, 7, 8, 9, " | $bindir/permute-square 

#0028.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0028.log
retval=$?

#cleanup
rm $expected
exit $retval
