#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
$bindir/small-seq-morgenstern-mn 100 | $bindir/small-morgenstern-search-type-8 100 >$expected

#generating our results
$bindir/seq-morgenstern-mn 100 | $bindir/morgenstern-search-type-8 100

#0041.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0041.log
retval=$?

#cleanup
rm $expected
exit $retval
