#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF | cut -f5,6,7 -d, | while IFS=, read col1 col2 col3; do r1=`echo "$col1 * $col1" | bc`; r2=`echo "$col2 * $col2" | bc`;r3=`echo "$col3 * $col3" | bc`; echo "$r3, $r2, $r1, " ; done > $expected
1, 1, 3, -2, -1, -1, 1, 0, 0
1, 3, 7, -8, -7, -5, -1, -24, -24
1, 5, 11, -18, -17, -13, -7, -120, -120
1, 7, 15, -32, -31, -25, -17, -336, -336
1, 9, 19, -50, -49, -41, -31, -720, -720
1, 11, 23, -72, -71, -61, -49, -1320, -1320
1, 13, 27, -98, -97, -85, -71, -2184, -2184
1, 15, 31, -128, -127, -113, -97, -3360, -3360
1, 17, 35, -162, -161, -145, -127, -4896, -4896
1, 19, 39, -200, -199, -181, -161, -6840, -6840
1, 21, 43, -242, -241, -221, -199, -9240, -9240
1, 23, 47, -288, -287, -265, -241, -12144, -12144
1, 25, 51, -338, -337, -313, -287, -15600, -15600
EOF

#generating our results
$bindir/find-3sq-progressions-gutierrez -n -- 13 1 3 2

#0051.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0051.log
retval=$?

#cleanup
rm $expected
exit $retval
