#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF | cut -f5,6,7 -d, | while IFS=, read col1 col2 col3; do r1=`echo "$col1 * $col1" | bc`; r2=`echo "$col2 * $col2" | bc`;r3=`echo "$col3 * $col3" | bc`; echo "$r3, $r2, $r1, " ; done > $expected
1, -3, 1, 1, 2, -2, 2, 0, 0
1, 1, 9, -5, -4, -4, 4, 0, 0
1, 5, 17, -15, -14, -10, 2, -96, -96
1, 9, 25, -29, -28, -20, -4, -384, -384
1, 13, 33, -47, -46, -34, -14, -960, -960
1, 17, 41, -69, -68, -52, -28, -1920, -1920
1, 21, 49, -95, -94, -74, -46, -3360, -3360
1, 25, 57, -125, -124, -100, -68, -5376, -5376
1, 29, 65, -159, -158, -130, -94, -8064, -8064
1, 33, 73, -197, -196, -164, -124, -11520, -11520
1, 37, 81, -239, -238, -202, -158, -15840, -15840
1, 41, 89, -285, -284, -244, -196, -21120, -21120
1, 45, 97, -335, -334, -290, -238, -27456, -27456
EOF

#generating our results
$bindir/find-3sq-progressions-gutierrez -un -- 13 -3 1 4

#0056.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0056.log
retval=$?

#cleanup
rm $expected
exit $retval
