#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF | cut -f5,6,7 -d, | while IFS=, read col1 col2 col3; do r1=`echo "$col1 * $col1" | bc`; r2=`echo "$col2 * $col2" | bc`;r3=`echo "$col3 * $col3" | bc`; echo "$r3, $r2, $r1, " ; done > $expected
1, -17, 1, 8, 9, -9, 9, 0
1, 1, 37, -19, -18, -18, 18, 0
1, 19, 73, -64, -63, -45, 9, -1944
1, 37, 109, -127, -126, -90, -18, -7776
1, 55, 145, -208, -207, -153, -63, -19440
1, 73, 181, -307, -306, -234, -126, -38880
1, 91, 217, -424, -423, -333, -207, -68040
1, 109, 253, -559, -558, -450, -306, -108864
1, 127, 289, -712, -711, -585, -423, -163296
1, 145, 325, -883, -882, -738, -558, -233280
1, 163, 361, -1072, -1071, -909, -711, -320760
1, 181, 397, -1279, -1278, -1098, -882, -427680
1, 199, 433, -1504, -1503, -1305, -1071, -555984
EOF

#generating our results
$bindir/find-3sq-progressions-gutierrez -n -- 13 -17 1 18

#0059.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0059.log
retval=$?

#cleanup
rm $expected
exit $retval
