#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF >$expected
10092, 3360, 4, 3364, 6724, 82, 
16428, 3360, 2116, 5476, 8836, 94, 
38307, 3360, 9409, 12769, 16129, 127, 
EOF


#generating our results
echo "3360" | $bindir/find-3sq-progressions-dist -d -s

#0065.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0065.log
retval=$?

#cleanup
rm $expected
exit $retval
