#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF >$expected
25, 241, 169, 289, 145, 1, 121, 49, 265, 
25, 241, 169, 289, 145, 1, 121, 265, 49, 
25, 241, 169, 289, 145, 1, 49, 265, 121, 
25, 241, 169, 289, 145, 1, 49, 121, 265, 
25, 241, 169, 289, 145, 1, 265, 121, 49, 
EOF


#generating our results
echo "25, 241, 169, 289, 145, 1, 121, 49, 265, " | $bindir/permute-square -S | head -n5

#0066.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0066.log
retval=$?

#cleanup
rm $expected
exit $retval
