#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src

cat << EOF >$expected
14917446769, 263153284, 9569926276, 8608499524, 5397253156, 10744773649, 1224580036, 19090119889, 4435826404, 
EOF


#generating our results

echo "12, 5" | $bindir/hillyer-square

#0082.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0082.log
retval=$?

#cleanup
rm $expected
exit $retval
