#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF >$expected
4, 4, 4, 2, 
1, 25, 49, 7, 
4, 100, 196, 14, 
49, 289, 529, 23, 
EOF


#generating our results

$bindir/find-3sq-progressions-conrad 5

#0088.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0088.log
retval=$?

#cleanup
rm $expected
exit $retval
