#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF >$expected
265, 1, 169, 49, 145, 241, 121, 289, 25, 
EOF


#generating our results

echo "265, 1, 169, 49, 145, 241, 121, 289, 25, " | $bindir/check-square

#0089.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0089.log
retval=$?

#cleanup
rm $expected
exit $retval
