#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF >$expected
49105, 2209, 28681, 6241, 26665, 47089, 24649, 51121, 4225, 
EOF


#generating our results

echo "2209, 24649, 47089, " | $bindir/3sq-pair-search 2209, 4225, 6241,

#0091.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0091.log
retval=$?

#cleanup
rm $expected
exit $retval
