#!/bin/bash
# Copyright (C) 2017 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/fituvalu.XXXXXX`
bindir=$builddir/../src
cat << EOF >$expected
1, 2, 3, 
EOF


#generating our results

echo "1, 2, 3, " | $bindir/convert-binary-gmp-records-to-text -n3 -i | $bindir/convert-binary-gmp-records-to-text -n3


#0092.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0092.log
retval=$?

#cleanup
rm $expected
exit $retval
